[package]
name = "lazin_test_macros"
version = "0.1.1"
edition = "2024"
description = "Simple macros for testing and non fatal asserts"
license = "MIT"
homepage = "https://github.com/HrvojeLesar/lazin"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3", features = ["full"] }
quote = "1"
lazin_test_utils = { path = "../lazin_test_utils", version = "0.1.1" }
